import {mkdir,readFile,writeFile,cp,rm} from 'node:fs/promises';
import {marked} from 'marked';
const origin='https://ddoktti-here.plead.co.kr';
const github='https://github.com/plead-ops/ddoktti-here';
function page(title,body,path='/') {return `<!doctype html>
<html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="화면 위를 산책하고, 필요한 순간에 소식을 전하는 작은 데스크톱 동료. Slack, Google Calendar, 타이머와 함께하는 똑띠왔어요."><meta name="theme-color" content="#f7f5ef"><meta name="slack-app-id" content="A0C539Q6E6B"><meta property="og:title" content="${title}"><meta property="og:description" content="당신의 하루에, 작은 동료 하나."><meta property="og:type" content="website"><meta property="og:url" content="${origin}${path}"><link rel="canonical" href="${origin}${path}"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/style.css"></head>
<body><a class="skip" href="#main">본문 바로가기</a><header class="header wrap"><a class="brand" href="/">똑띠왔어요<span class="brand-dot"></span></a><nav aria-label="주 메뉴"><a href="/#features">함께하는 일</a><a href="/#privacy">개인정보</a><a class="nav-github" href="${github}">GitHub ↗</a></nav></header>${body}
<footer class="wrap"><div><a class="brand" href="/">똑띠왔어요</a><p>당신의 하루에, 작은 동료 하나.<br>플리드(Plead) · 똑띠왔어요 프로젝트</p></div><nav aria-label="하단 메뉴"><a href="/privacy">개인정보처리방침</a><a href="/terms">이용약관</a><a href="${github}/issues">문의하기 ↗</a></nav><small>© ${new Date().getFullYear()} 똑띠왔어요. Slack과 Google의 공식 제품이 아닙니다.</small></footer></body></html>`;}
const home=`<main id="main"><section class="hero wrap"><div class="hero-copy"><span class="pill"><i></i> Windows · macOS</span><h1>똑똑,<br>당신의 하루에<br><em>똑띠 왔어요.</em></h1><p>혼자 일하는 화면에도 작은 동료가 필요하니까.<br>이리저리 산책하다가, 꼭 필요한 순간에<br>소식을 전해드릴게요.</p><div class="actions"><a class="button" href="${github}">똑띠 프로젝트 둘러보기 <span>↗</span></a><a class="text-link" href="#features">어떤 친구인가요? ↓</a></div><p class="release-note">공개 배포 준비 중 · 계정 연동은 검증을 진행하고 있어요.</p></div><div class="hero-art" aria-label="반갑게 인사하는 똑띠 캐릭터"><div class="art-circle"></div><span class="spark one">✦</span><span class="spark two">✧</span><div class="hello">안녕! 오늘도 함께할게요.<span></span></div><img class="hero-pet" src="/assets/pet.svg" width="300" height="330" alt="짧은 다리와 안테나가 있는 똑띠 캐릭터"><div class="pet-shadow"></div><div class="desktop-line"><span></span><span></span><span></span><p>작은 발걸음으로, 곁에.</p></div></div></section>
<section class="intro wrap"><span class="section-mark">함께, 똑띠답게</span><h2>알림이 없을 때도<br>곁에 있는 친구.</h2><p>걷다가, 쉬다가, 꾸벅 졸기도 해요.<br>살짝 클릭하면 간지러워하고, 졸 때는 깜짝 놀라 깨어나요.<br>필요할 때만 만나고 싶다면 알림 전용 모드도 있어요.</p></section>
<section id="features" class="features wrap"><article class="feature green"><div class="feature-icon" aria-hidden="true">↗</div><h3>놓치고 싶지 않은 메시지</h3><p>Slack의 DM과 나를 찾는 멘션을<br>말풍선으로 살며시 알려드려요.</p><div class="message"><span class="avatar">동</span><div><strong>동료에게 온 메시지</strong><p>이번 작업, 같이 확인해 볼까요?</p></div></div><p class="fine">공개 채널의 개인·그룹·전체 멘션과 DM을 지원합니다. 비공개 채널·그룹 DM은 지원하지 않습니다.</p></article><article class="feature peach"><div class="feature-icon" aria-hidden="true">◷</div><h3>다음 약속도, 잊지 않게</h3><p>Google Calendar에서 내가 포함된<br>일정을 찾아 미리 챙겨드려요.</p><div class="calendar"><span>14:00</span><div><strong>팀 주간 미팅</strong><p>잠시 뒤 시작해요</p></div><b aria-hidden="true">↗</b></div><p class="fine">새로 추가한 캘린더와 응답 전 초대도 확인합니다. 읽기 권한만 사용하고 중복 알림을 줄입니다.</p></article><article class="feature cream"><div class="feature-icon" aria-hidden="true">☕</div><h3>집중할 때도, 쉴 때도</h3><p>타이머로 집중 시간을 만들고<br>가끔은 함께 기지개를 켜요.</p><div class="timer">25<span>:</span>00<small>지금은 집중하는 시간</small></div><p class="fine">계정 연결 없이도 타이머와 스트레칭 안내를 사용할 수 있어요.</p></article></section>
<section class="connect wrap"><div><span class="section-mark">가볍게 시작해요</span><h2>만나는 방법은<br>어렵지 않아요.</h2></div><ol><li><span>01</span><div><h3>함께할 방식을 골라요</h3><p>항상 곁에 둘지, 알림이 있을 때만 만날지 선택하세요.</p></div></li><li><span>02</span><div><h3>필요한 계정만 연결해요</h3><p>앱에서 ‘Slack에 추가하고 연결’ 또는 ‘Google Calendar 연결’을 누르고 브라우저에서 승인해 주세요. 조직 정책에 따라 관리자 승인이 필요할 수 있어요.</p></div></li><li><span>03</span><div><h3>나머지는 똑띠에게</h3><p>알림 필터와 쉬는 시간을 설정하면 준비 끝. 연결은 언제든 해제할 수 있어요.</p></div></li></ol></section>
<section id="privacy" class="privacy wrap"><div class="privacy-pet"><img src="/assets/sleepy.svg" width="150" height="160" alt="편안하게 쉬는 똑띠" loading="lazy"></div><div><span class="section-mark">안심하고 함께하도록</span><h2>필요한 정보만,<br>필요한 곳에서.</h2><p>Google 일정은 내 PC에서 직접 조회하고, 똑띠 서버로 보내지 않아요. Slack 알림은 중계 서버에서 판별하고 잠시 보관해 전달해요. 메시지와 일정을 광고나 AI 학습에 사용하지 않아요.</p><a class="text-link" href="/privacy">정보 처리와 삭제 방법 읽기 →</a></div></section>
<section class="closing wrap"><h2>작지만, 든든한 존재가 될게요.</h2><p>똑띠는 지금 더 좋은 동료가 되는 중이에요.<br>개발 현황과 배포 소식을 GitHub에서 확인해 주세요.</p><a class="button" href="${github}">GitHub에서 만나기 ↗</a></section></main>`;
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
await writeFile('dist/index.html',page('똑띠왔어요 — 당신의 하루에, 작은 동료 하나',home));
for(const slug of ['privacy','terms']){
 let md=await readFile(`content/${slug}.md`,'utf8');
 md=md.replaceAll('(README.md)','(/)').replaceAll('(PRIVACY.md)','(/privacy)').replaceAll('(TERMS.md)','(/terms)');
 const title=slug==='privacy'?'개인정보처리방침':'이용약관';
 await mkdir(`dist/${slug}`,{recursive:true});
 await writeFile(`dist/${slug}/index.html`,page(`${title} · 똑띠왔어요`,`<main id="main" class="legal wrap"><a class="text-link" href="/">← 똑띠 소개로 돌아가기</a><article>${marked.parse(md)}</article></main>`,`/${slug}`));
}
await writeFile('dist/404.html',page('페이지를 찾을 수 없어요 · 똑띠왔어요','<main id="main" class="legal wrap"><h1>여기는 똑띠가 아직 가보지 못했어요.</h1><a class="button" href="/">홈으로 돌아가기</a></main>'));
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/privacy','/terms'].map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')}</urlset>`);
console.log('Built homepage, privacy policy and terms');
